// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hroqwcgekazpeaybwfbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhyb3F3Y2dla2F6cGVheWJ3ZmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzA0MjMsImV4cCI6MjA2OTU0NjQyM30.HZlVseJ-JOfqSqeD855RoaYDc91YMslKbS_1v9JGxjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});